camera_info:
  image_width: 800
  image_height: 600
stop_line_positions:
    - [1148.56, 1184.65]
    - [1559.2, 1158.43]
    - [2122.14, 1526.79]
    - [2175.237, 1795.71]
    - [1493.29, 2947.67]
    - [821.96, 2905.8]
    - [161.76, 2303.82]
    - [351.84, 1574.65]
is_site: False
use_light_state: False
lookahead_waypoints: 100
classifier:
  threshold: 0.5
  model_path: "models/ssd_mobilenet_v2/graph_optimized.pb"
