camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
is_site: True
use_light_state: False
lookahead_waypoints: 100
classifier:
  threshold: 0.5
  model_path: "models/ssd_mobilenet_v2/graph_optimized.pb"
